name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.1
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipreqs
        pipreqs .
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest tests/

    # Commenting out the main script run as it requires MongoDB
    # - name: Run main script
    #   run: |
    #     python main.py